name: CI tests and checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip3 install pip-tools
    - run: pip-sync requirements/requirements.txt
    - run: make test
    - run: make black
    - run: make slowtest
    - run: make pylint
    - run: make -C doc html linkcheck
